title: Lisa Gaudette # your name (or website title) here
#logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Welcome to the home of my side projects!
  <br/>
  <ul>
  <li><a href="OCTrainsfer">OC Trainsfer App</a></li>
  <li><a href="Projects">Other Projects</a></li>
  <li><a href="https://www.linkedin.com/in/lisagaud/">LinkedIn Profile</a></li>
  </ul>

show_downloads: false
theme: jekyll-theme-minimal